version: '3'  #actaullyworks! first version using terraform on aws without cicd and k8s, tommarow we tackle the pipeline!
services:
  flaskgif:
    build:
      context: .
      dockerfile: Dockerfile
    image: yuvalbenar/terraflaskqlk8s:latest
    container_name: flaskgif
    ports:
      - "5000:5000"
    depends_on:
      - gif-db
    networks:
      - flaskapp-network
 

  gif-db:
    image: mysql:5.7
    container_name: gif-db
    ports:
      - "3308:3306"
    networks:
      - flaskapp-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    

networks:
  flaskapp-network:
    driver: bridge  # Define the network with a driver (bridge is common for local setups)

volumes:
  mysql-data:  # Ensure the volume is also defined if you plan to persist MySQL data
