version: '3'
services:
  flaskgif:
    build:
      context: .
      dockerfile: Dockerfile
    image: yuvalbenar/terraflaskqlk8s:latest
    container_name: flaskgif
    ports:
      - "5000:5000"
    depends_on:
      - gif-db
    networks:
      - flaskapp-network

  gif-db:
    image: mysql:5.7
    container_name: gif-db
    ports:
      - "3308:3306"
    networks:
      - flaskapp-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
  flaskapp-network:
    driver: bridge

volumes:
  mysql-data:
