apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask
spec:
  replicas: 2  # Running two instances for redundancy
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: yuvalbenar/flasksqlgifbase:v1.0.83  # Update if needed
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: database_host
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets  # Updated to match the new secret name
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets  # Updated to match the new secret name
                  key: password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets  # Updated to match the new secret name
                  key: database_name
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: flask_env
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000  # External port
      targetPort: 5000  # Container port
  type: LoadBalancer  # Expose using LoadBalancer
