apiVersion: apps/v1
kind: Deployment
metadata:
  name: gif-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gif-db
  template:
    metadata:
      labels:
        app: gif-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: root_password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: database_name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: init-db-volume
          mountPath: /docker-entrypoint-initdb.d/init-db.sql
          subPath: init-db.sql
      volumes:
      - name: init-db-volume
        configMap:
          name: mysql-config

---
apiVersion: v1
kind: Service
metadata:
  name: gif-db
spec:
  selector:
    app: gif-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None  # Allows internal communication via DNS
