apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flask.name }}
  labels:
    app: flask
spec:
  selector:
    app: flask
  ports:
    - name: {{ .Values.flask.service.portName | default "http" }}
      protocol: TCP
      port: {{ .Values.flask.service.port }}
      targetPort: {{ .Values.flask.containerPort }}
  type: {{ .Values.flask.service.type }}
