apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flask.name }}
  labels:
    app: flask   # Ensure consistency across related resources
spec:
  selector:
    matchLabels:  # <-- Ensure correct selector format
      app: flask
  ports:
    - name: http    # Port name must match ServiceMonitor endpoint
      protocol: TCP
      port: {{ .Values.flask.service.port }}
      targetPort: {{ .Values.flask.containerPort }}
  type: {{ .Values.flask.service.type }}
