apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flask.name }}
  labels:
    app: flask   # Ensure consistency across related resources
spec:
  selector:
    app: flask  # ✅ Correct selector format (key-value pair)
  ports:
    - name: http    # Port name must match ServiceMonitor endpoint
      protocol: TCP
      port: {{ .Values.flask.service.port }}
      targetPort: {{ .Values.flask.containerPort }}
  type: {{ .Values.flask.service.type }}
