apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flask.name }}
  labels:
    app: flask  # Explicit label for ServiceMonitor selection
spec:
  selector:
    app: flask
  ports:
    - name: {{ .Values.flask.service.portName | default "http" }}  # Uses the value from values.yaml, defaulting to "http" if not set 
    - protocol: TCP
      port: {{ .Values.flask.service.port }}
      targetPort: {{ .Values.flask.containerPort }}
  type: {{ .Values.flask.service.type }}
  	