apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flask.name }}
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: {{ .Values.flask.service.port }}
      targetPort: {{ .Values.flask.containerPort }}
  type: {{ .Values.flask.service.type }}
