apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
spec:
  selector:
    app: {{ .Values.mysql.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.containerPort }}
      targetPort: {{ .Values.mysql.containerPort }}
  clusterIP: None  # For headless service
