apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask
  namespace: monitoring
  labels:
    release: my-monitoring
spec:
  selector:
    matchLabels:
      app: flask    # Updated to match your Service label
  endpoints:
    -ports:
     - name: http   # <--- Add this
       port: 5000
       targetPort: 5000

      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
