apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  namespace: monitoring
  labels:
    release: my-monitoring
spec:
  selector:
    matchLabels:
      app: flask  # Matches the Service label
  endpoints:
    - port: http  # 🟢 Corrected indentation & removed `-ports`
      targetPort: 5000
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
