apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  namespace: monitor  # The namespace where Prometheus is installed
spec:
  selector:
    matchLabels:
      app: flask-app  # This matches the label we just added
  endpoints:
    - port: http  # Make sure your service port has this name; if not, update it accordingly
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default  # The namespace where your Flask app is deployed
