apiVersion: v2
name: flasksql-chart
description: A Helm chart for deploying a Flask application with a MySQL backend.
type: application
version: 0.0.${{ github.run_number }}  # could this be the run?
appVersion: "1.0"
keywords:
  - flask
  - mysql
  - helm
  - kubernetes
home: https://github.com/yuvalbenar/terraflaskqlk8s/tree/k8sdeploy
sources:
  - https://github.com/yuvalbenar/terraflaskqlk8s/tree/k8sdeploy
maintainers:
  - name: Yuval Ben Ari
    email: yuvalbenar@gmail.com
